sudo: required
services: 
  - docker

before_install: 
  - docker build -t porvas/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run porvas/react-test npm test -- --coverage

after_success:
  - docker build -t porvas/multi-client -f ./client
  - docker build -t porvas/multi-nginx -f ./nginx
  - docker build -t porvas/multi-server -f ./server
  - docker build -t porvas/multi-worker -f ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin 
  # take those images and push them to docker hub
  - docker push porvas/multi-client
  - docker push porvas/multi-nginx
  - docker push porvas/multi-server
  - docker push porvas/multi-worker