name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the dev docker image
      run: docker build -t pvasileiou/react-test -f ./client/Dockerfile.dev ./client
    - name: Run tests
      run: docker run -e CI=true pvasileiou/react-test npm test
    - name: Build the Docker images
      run: docker build -t pvasileiou/multi-client ./client
    - name: Build the Docker images
      run: docker build -t pvasileiou/multi-nginx ./nginx
    - name: Build the Docker images
      run: docker build -t pvasileiou/multi-server ./server
    - name: Build the Docker images
      run: docker build -t pvasileiou/multi-worker ./worker
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_ID}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_ACCESS_TOKEN}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
    - name: Docker Push
      run: docker push pvasileiou/multi-client 
    - name: Docker Push
      run: docker push pvasileiou/multi-nginx 
    - name: Docker Push
      run: docker push pvasileiou/multi-server 
    - name: Docker Push
      run: docker push pvasileiou/multi-worker
    
    - name: Generate deployment package
      run: zip -r deploy.zip . -x '*.git*'

    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v20
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: multi-docker
        environment_name: Multidocker-env
        version_label: 1
        region: eu-central-1
        version_description: ${{github.SHA}}
        use_existing_version_if_available: true
        existing_bucket_name: elasticbeanstalk-eu-central-1-190385190527
        deployment_package: deploy.zip
