name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the dev docker image
      run: docker build -t pvasileiou/react-test -f ./client/Dockerfile.dev ./client
    - name: Run tests
      run: docker run -e CI=true pvasileiou/react-test npm test
    - name: Build the Docker images
      run: docker build -t pvasileiou/multi-client -f ./client
        | docker build -t pvasileiou/multi-nginx -f ./nginx
        | docker build -t pvasileiou/multi-server -f ./server
        | docker build -t pvasileiou/multi-worker -f ./worker
